
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class FrameProgram extends javax.swing.JFrame {

    /**
     * Creates new form FrameProgram
     */
    public FrameProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ButtonBola = new javax.swing.JButton();
        JariBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ButtonKubus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tbalok = new javax.swing.JTextField();
        Pbalok = new javax.swing.JTextField();
        Lbalok = new javax.swing.JTextField();
        ButtonBalok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 400, 30);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 30, 190, 30);

        ButtonBola.setText("Volume");
        ButtonBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBolaActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBola);
        ButtonBola.setBounds(30, 120, 80, 30);

        JariBola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(JariBola);
        JariBola.setBounds(30, 70, 90, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(130, 70, 30, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 30, 150, 30);

        SisiKubus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SisiKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisiKubusActionPerformed(evt);
            }
        });
        jPanel1.add(SisiKubus);
        SisiKubus.setBounds(30, 70, 90, 30);

        jLabel9.setText("cm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 70, 30, 30);

        ButtonKubus.setText("Volume");
        ButtonKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKubusActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonKubus);
        ButtonKubus.setBounds(30, 120, 80, 30);

        jTabbedPane1.addTab("Kubus", jPanel1);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Masukkan Tinggi        :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 110, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan Panjang    :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 30, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan Lebar        :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 70, 130, 30);

        jLabel5.setText("cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 110, 30, 30);

        jLabel6.setText("cm");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 30, 30, 30);

        jLabel7.setText("cm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(260, 70, 30, 30);

        Tbalok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbalokActionPerformed(evt);
            }
        });
        jPanel2.add(Tbalok);
        Tbalok.setBounds(170, 110, 80, 30);

        Pbalok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbalokActionPerformed(evt);
            }
        });
        jPanel2.add(Pbalok);
        Pbalok.setBounds(170, 30, 80, 30);

        Lbalok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbalokActionPerformed(evt);
            }
        });
        jPanel2.add(Lbalok);
        Lbalok.setBounds(170, 70, 80, 30);

        ButtonBalok.setText("Hitung");
        ButtonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBalokActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonBalok);
        ButtonBalok.setBounds(30, 150, 70, 30);

        jTabbedPane1.addTab("Balok", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 400, 270);

        setBounds(0, 0, 416, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void TbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbalokActionPerformed

    private void PbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PbalokActionPerformed

    private void LbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LbalokActionPerformed

    private void SisiKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisiKubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SisiKubusActionPerformed

    private void ButtonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBalokActionPerformed
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(Pbalok.getText());
        lebar = Integer.parseInt(Lbalok.getText());
        tinggi = Integer.parseInt(Tbalok.getText());
        int hasil = panjang*lebar*tinggi;
        
        try
        {
            JOptionPane.showMessageDialog(null,"Volume Balok adalah : " + hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error!" + e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_ButtonBalokActionPerformed

    private void ButtonKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKubusActionPerformed
        int sisi;
        sisi = Integer.parseInt(SisiKubus.getText());
        int hasil = sisi*sisi*sisi;
        
        try
        {
            JOptionPane.showMessageDialog(null,"Volume Kubus adalah : " +hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error!" +e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonKubusActionPerformed

    private void ButtonBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBolaActionPerformed
        int jari;
        jari = Integer.parseInt(JariBola.getText());
        float hasil = (float) (4/3*3.14*jari*jari*jari);
        
        try
        {
            JOptionPane.showMessageDialog(null, "Volume Bola adalah : " + hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error!"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_ButtonBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBalok;
    private javax.swing.JButton ButtonBola;
    private javax.swing.JButton ButtonKubus;
    private javax.swing.JTextField JariBola;
    private javax.swing.JTextField Lbalok;
    private javax.swing.JTextField Pbalok;
    private javax.swing.JTextField SisiKubus;
    private javax.swing.JTextField Tbalok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
